### ISSUE TITLE
add original names as doc aliases to functions

### ISSUE THREAD

**Issue by benmkw** [4bb4/implot-rs#11]
https://blog.rust-lang.org/2020/11/19/Rust-1.48.html#adding-search-aliases

> An interesting use case for aliases is FFI wrapper crates, where each Rust function could be aliased to the C function it wraps. Existing users of the underlying C library would then be able to easily search the right Rust functions!

I think this is a good idea and I should do the same for imnodes/ I already put the names in the comments. My approach was to basically tag a function with the name of every native function that gets called inside it.

**Comment by 4bb4** [comment]
Good idea, I thought that too reading the 1.48 announcement.

**Comment by 4bb4** [comment]
Most aliases should have been added at this point. Will add more when I come across them.
