### ISSUE TITLE
Update to Imgui-rs 0.7.0 and create a new release

### ISSUE THREAD

**Issue by 4bb4** [4bb4/implot-rs#13]
There has been a [new release](https://github.com/imgui-rs/imgui-rs/blob/master/CHANGELOG.markdown#070---2021-02-04) of imgui-rs with new features, so I plan to update to that once I figure out everything still works ok. This is also a good time to create a new release.

**Comment by 4bb4** [comment]
This is now WIP in https://github.com/4bb4/implot-rs/tree/13-upgrade-to-imgui-rs-0.7, pending https://github.com/Yatekii/imgui-wgpu-rs/pull/44.

**Comment by a1ien** [comment]
What we wait? imgui-wgpu-rs was released

**Comment by 4bb4** [comment]
As long as the issue in https://github.com/Yatekii/imgui-wgpu-rs/pull/44 is not fixed, we can't upgrade. I have not been able to invest any time in investigating the issue enough to fix the problem yet. You're free to investigate and fix the problem yourself and submit a fix if you would like things to advance more quickly.

**Comment by 4bb4** [comment]
An update on this: I'm not able to create a release for imgui-rs 0.7 yet, because the upgrade to imgui-wgpu-rs that comes along with it makes it so that (at least for me, but very reproducibly on multiple machines) I get the crash I described in https://github.com/Yatekii/imgui-wgpu-rs/pull/44 when running the WGPU example.

I have however spent more time trying to debug things and had the following results:
* The crash reliably happens when I run the example, then open a few of the tabs with example plots and scroll up and down in the window.
* No resizing of any kind is necessary to reproduce this crash, neither of the system window nor the "imgui window" containing the demo headers. This seems important because I at first thought that @Uriopass ran into the same problem I have over in https://github.com/Yatekii/imgui-wgpu-rs/issues/48, but there it seems to be related to resizing of windows.
* The problem happens both in my example code, but also when I open the (implemented-in-C++) demo window that implot itself provides.

These findings lead me to believe that there may be some sort of reporting of how big things that are drawn are, or which section of them is to be drawn, of implot to imgui, and that part may be done wrong in a way that only trips up WGPU but not the other backends - or maybe imgui 0.7 points to a newer C++ version of imgui that changes some things, and the old implot code I point to has an incompatibility there.

I've also attempted to intercept the error and ignore it, as @francesco-cattoglio proposed in https://github.com/Yatekii/imgui-wgpu-rs/pull/44#issuecomment-783465728 - I got some version of that to work in a prototype, but adding some printing showed that this happens so often that I'm not really comfortable with that fix and would prefer to get a better understanding.

**Comment by benmkw** [comment]
> These findings lead me to believe that there may be some sort of reporting of how big things that are drawn are, or which section of them is to be drawn, of implot to imgui, and that part may be done wrong in a way that only trips up WGPU but not the other backends

this was also my hypothesis but I did not investigate it further yet/ probably need to look at the drawing code of implot

wgpu 0.8 will apparently soon be released maybe this will improve/ change the debugging output (I have no specific information/ just something to look out for maybe)

**Comment by 4bb4** [comment]
It seems other people came across the same ScissorRect problem in unrelated applications (see the linked issue, for example). I've upgraded `imgui-wgpu` and `wgpu-rs` on the branch I have here and re-tested things, the issue is still there.

**Comment by kylc** [comment]
This issue should be fixed in imgui-wgpu 0.17 :tada:

**Comment by 4bb4** [comment]
Reopening this, because there is no new release yet.

**Comment by 4bb4** [comment]
@kylc would you like a new release or are you fine with pointing to the git repo here for the moment? If you don't need a release for now, I think I'll do some more experiments with updating the cimplot pin to a newer version first. If you do though, I can make one and then do my experiments after that.

**Comment by asayers** [comment]
Just FYI, imgui-rs 0.8 is apparently scheduled for release on Thursday.  It might make sense to do a 0.7-compatible release of implot-rs anyway, just in case there are people who can't/don't want to upgrade to 0.8.

EDIT: source: https://github.com/imgui-rs/imgui-rs/issues/462#issuecomment-919254900

**Comment by kylc** [comment]
@4bb4 I don't have any immediate need for a release. Thank you for asking!

**Comment by 4bb4** [comment]
> Just FYI, imgui-rs 0.8 is apparently scheduled for release on Thursday

Awesome, thanks for the heads-up, I had not seen that conversation yet. I'll keep that in mind and make sure to create a release with 0.7 before moving to 0.8.

**Comment by 4bb4** [comment]
I've created a 0.6.0 release, which still points to imgui-rs 0.7.0, so I'm closing the issue here. Work will now start on moving to imgui-rs 0.8.0, and at the same time on moving to a newer cimplot.
